[logging]
debug = true

[database]
graphannis = "/home/thomas/.annis/v4"
sqlite = "/home/thomas/.annis/v4/service_data.sqlite3"
query_timeout = 60

[auth.token_verification]
type = "HS256"
secret = "<some-very-private-and-secret-key>"
