# Replace file contents only once
pre-release-replacements = [
  {file = "../CHANGELOG.md", search = "## \\[Unreleased\\]", replace = "## [Unreleased]\n\n## [{{version}}] - {{date}}"},
  {file = "../CITATION.cff", search = "^version: [0-9.]+", replace = "version: {{version}}"},
  {file = "../CITATION.cff", search = "date-released: [0-9\\-]+", replace = "date-released: {{date}}"},
  {file = "../docs/src/embed-rust.md", search = "graphannis = \"[0-9.]+\"", replace = "graphannis = \"{{version}}\""},
]
tag-name = "v{{version}}"
