set(VC_PREFIX ${GLOBAL_OUTPUT_PATH}/vc)


ExternalProject_Add(
  VC

  UPDATE_COMMAND ""
  PATCH_COMMAND ""

  SOURCE_DIR "${CMAKE_SOURCE_DIR}/ext/Vc-1.3.1"
  CMAKE_ARGS -BUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=True -DCMAKE_INSTALL_PREFIX=${VC_PREFIX}

  TEST_COMMAND ""
)


set(VC_INCLUDE_DIRS "${VC_PREFIX}/include")
set(VC_LIBRARIES "${VC_PREFIX}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}Vc${CMAKE_STATIC_LIBRARY_SUFFIX}")

include_directories(SYSTEM ${VC_INCLUDE_DIRS})
