on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    
name: Static code analysis
jobs:
  static_code_analysis:
    name: "Static code analysis"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          components: clippy, rustfmt
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: -- --check
      - uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
