on: push
name: Static code analysis
jobs:
  static_code_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
      - uses: Swatinem/rust-cache@v1.3.0
      - run: rustup component add clippy rustfmt
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: -- --check
      - uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
